name: Generate Build Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Save Artifact for Download
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: |
            dist
            build
            out
            .output
            public
          include-hidden-files: true
